<a href="https://colab.research.google.com/github/Elsaterziu/ml-project/blob/main/patient_no_show_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving appointments.csv to appointments.csv

In [2]:
import pandas as pd

df = pd.read_csv("appointments.csv")
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

ScheduledDay      0
AppointmentDay    0
dtype: int64

,Gender,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Handicap,SMS_received,WaitingDays,AppointmentWeekDay,ScheduledHour,NoShow
0,F,62,JARDIM DA PENHA,0,1,0,0,0,0,0,4,18,0
1,M,56,JARDIM DA PENHA,0,0,0,0,0,0,0,4,16,0
2,F,62,MATA DA PRAIA,0,0,0,0,0,0,0,4,16,0
3,F,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0,4,17,0
4,F,56,JARDIM DA PENHA,0,1,1,0,0,0,0,4,16,0

In [8]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 110521 entries, 0 to 110526
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Gender              110521 non-null  object
 1   Age                 110521 non-null  int64
 2   Neighbourhood       110521 non-null  object
 3   Scholarship         110521 non-null  int64
 4   Hypertension        110521 non-null  int64
 5   Diabetes            110521 non-null  int64
 6   Alcoholism          110521 non-null  int64
 7   Handicap            110521 non-null  int64
 8   SMS_received        110521 non-null  int64
 9   WaitingDays         110521 non-null  int64
 10  AppointmentWeekDay  110521 non-null  int32
 11  ScheduledHour       110521 non-null  int32
 12  NoShow              110521 non-null  int64
dtypes: int32(2), int64(9), object(2)
memory usage: 11.0+ MB

In [6]:
df_cleaned.isnull().sum()

Gender                0
Age                   0
Neighbourhood         0
Scholarship           0
Hypertension          0
Diabetes              0
Alcoholism            0
Handicap              0
SMS_received          0
WaitingDays           0
AppointmentWeekDay    0
ScheduledHour         0
NoShow                0
dtype: int64

In [7]:
df_cleaned.shape

(110521, 13)

In [9]:
df_cleaned.to_csv("appointments_cleaned.csv", index=False)

In [10]:
from google.colab import files
files.download("appointments_cleaned.csv")